#' For oredered distribution of ensembles for pathogen pairs, should be able to run 
#' With an empty global emv 

library(dplyr)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(copathogenTools)
source(file.path("scripts", "load_all_results.R"))

two_var_coloring <- c("#1f78b4", "#67D067")
CO_MINIMUM <- 10


##### Functions ####
plot_pathogen_pair_distribution <- function(ensembles, output){
  rank_cutoff <- 0.50
  
  for(s in c("Diarrhea", "Asymptomatic")){
    
    ordered_plot <- ensembles %>% ungroup() %>%
      readable_path_names(formatted = T) %>%
      # filter_out_nonsymmetric() %>%
      mutate(pathogen_pair = paste(path1, path2, sep = " + ")) %>%
      filter(stool_type == s, actual > CO_MINIMUM) %>%
      select(pathogen_pair, study, stool_type, actual, distance_rank_n) %>%
      distinct() %>%
      group_by(pathogen_pair) %>%
      summarise(
        ave_rank = mean(distance_rank_n),
        n_pairs = n_distinct(study)) %>%
      ungroup() %>%
      filter(
        n_pairs > 1) %>%
      slice_min(ave_rank, n = 43) %>% # 43 is a hard coding 10%,
      arrange(ave_rank)
    
    # View(ordered_plot, title = s)
    
    data_subset <- ensembles %>%
      filter(stool_type == s) %>% 
      readable_path_names(formatted = T) %>% 
      mutate(pathogen_pair = paste(path1, path2, sep = " + ")) %>% 
      group_by(pathogen_pair, stool_type) %>% 
      mutate(combined_label = factor(pathogen_pair, levels = unique(ordered_plot$pathogen_pair)))

    if(output == "local"){
      plot_list <- lapply(ordered_plot$pathogen_pair[1], plot_standardised_histogram, data_subset = data_subset)
    }else{
      plot_list <- lapply(unique(ordered_plot$pathogen_pair), plot_standardised_histogram, data_subset = data_subset)
      
    }
    plot_list <- plot_list[!vapply(plot_list, is.null, logical(1))]
    if(output == "local"){
      grid.arrange(grobs = plot_list, nrow = 1,
                   # top = grid::textGrob(paste("Co-infection Ensemple for", s, "stools"), 
                   #                      gp = grid::gpar(fontsize=72, fontface="bold",lineheight=1))
      )
    }else if(output == "pdf"){
      # if(basename(getwd()) != "copathogen-ensembles"){
      #   pdf_path <- file.path("..", "figures", "copathogen_distributions_")
      # }else{
        pdf_path <- file.path("figures", "copathogen_distributions_")
      # }
      
      
      # Commented out 17Jul21  
      # print(length(plot_list))
      # pdf(paste0(pdf_path, s, ".pdf"), width = 20, height = ceiling(length(plot_list)/4) * 3.8, onefile = F)
      # grid.arrange(grobs = plot_list, ncol = 4,  
      #              top = grid::textGrob(paste("Co-infection Ensemble for", s, "stools"), 
      #                                   gp = grid::gpar(fontsize=36, fontface="bold",lineheight=1)))
      # dev.off()
      # 
      pdf(paste0(pdf_path, s, "top_12_09Jun22", ".pdf"), width = 20, height = ceiling(length(plot_list)/4) * 3.8 * (3/11), onefile = F)
      grid.arrange(grobs = plot_list[1:12], ncol = 4,
                   top = grid::textGrob("", gp = grid::gpar(fontsize=36, fontface="bold",lineheight=1)))
      dev.off()
      
      
      # for(i in 1:length(plot_list)){
      #   pdf(file.path("figures", "all_ensembles", tolower(s), paste0(paste(s, i, sep = "_"), ".pdf")), width = 6, height = 4 , onefile = F)
      #   print(plot_list[[i]])
      #   dev.off()
      # }
    }
  }
  
}


read_in_ensemble <- function(filename, results, study_option, stool_type_option, include_percentiles){
  #' @title Import ensembles from configuration model
  #' 
  #' @description Import and ensemble from the configuration model generated by
  #' rewirign the matrix. Reads in a csv file, which contains a column for each pathogen pair, 
  #' where ordering matters, therefore  P! columns, where P is the number of species, and rows are the 
  #' number of replicates. 
  #' 
  #' 
  #' 
  file_location <- file.path("data", "null_ensembles", "full_ensembles", filename)
  
  results_idx <- results %>% 
    mutate(combined = paste(path1, path2, sep = "+")) %>% 
    filter(stool_type == stool_type_option, study == study_option)
  
  if(!include_percentiles){
    results_idx <- results_idx %>% filter_out_nonsymmetric()
  }
  
  temp <- readr::read_csv(file_location) %>% group_by(timepoint) %>%  mutate(replicate = sequence(n())) %>% 
    tidyr::pivot_longer(cols = contains("+"), names_to = "pathogen_pair", values_to = "num_co")# %>%
    # filter(pathogen_pair %in% results_idx$combined) %>% 
  # tidyr::separate("pathogen_pair", into = c("path1", "path2"), sep = "\\+", remove = FALSE)
  
  print(nrow(temp))
  
  if(include_percentiles){
    temp <- temp %>% left_join(
      results_idx %>% 
        filter(stool_type == stool_type_option, study == study_option) %>% ungroup() %>% 
        select(combined, actual, percentile, percentile_rank_n, distance_rank_n) %>% 
        rename(pathogen_pair = combined), by = "pathogen_pair") %>% 
      mutate(stool_type = stool_type_option, study = study_option)
    
    print(nrow(temp))
  }else{
    temp <- temp %>% left_join(
      results_idx %>% 
        filter(stool_type == stool_type_option, study == study_option) %>% ungroup() %>% 
        select(combined, actual) %>% 
        rename(pathogen_pair = combined), by = "pathogen_pair") %>% 
      mutate(stool_type = stool_type_option, study = study_option)
  }
  
  temp <- temp %>% 
    filter(!is.na(percentile_rank_n)) %>% 
    tidyr::separate("pathogen_pair", 
                    into = c("path1", "path2"), 
                    sep = "\\+", remove = FALSE)
  
  return(temp)
}

plot_standardised_histogram <- function(pathogens, data_subset){
  data_subset <- data_subset[which(data_subset$combined_label == pathogens),]
  if(length(unique(data_subset$study)) < 2 | nrow(data_subset) == 0){
    return(NULL)
  }
  
  dist_ranks <- list()
  
  hist_plot <- ggplot() + 
    geom_vline(
      data = data.frame(),
      xintercept = c(-1.96, 1.96),
      color = "black",
      size = 0.8,
      linetype = "dotted"
    )+
    geom_vline(
      data = data.frame(),
      xintercept = c(-2.33, 2.33),
      color = "black",
      size = 0.8,
      linetype = "dashed"
    )
  
  for(study_var in unique(data_subset$study)){
    bin_width <- 10
    temp_df <- data_subset %>% filter(study == study_var)
    
    temp_df$std_co <- (temp_df$num_co - mean(temp_df$num_co))/ sd(temp_df$num_co)
    
    if(is.infinite(max(temp_df$num_co)) | is.infinite(min(temp_df$std_co)) | sum(is.na(temp_df$std_co)) > 0){
      View(data_subset)
      print(nrow(temp_df))
      print(unique(data_subset$study))
      print(pathogens)
    }
    if(is.infinite( min(temp_df$std_co))){
      # View(temp_df)
    }
    bin_sequence <- unique(c(seq(0, min(temp_df$std_co), -sd(temp_df$std_co)/bin_width), 
                             seq(0, max(temp_df$std_co), sd(temp_df$std_co)/bin_width)))
    
    
    # Lines that mark the actual position of the observed number of co-occurences
    actual_obs_markers <- temp_df %>% ungroup() %>% mutate(actual_std = (actual - mean(num_co))/sd(num_co)) %>% 
      select(pathogen_pair, actual_std, study, stool_type, combined_label, percentile, distance_rank_n, actual) %>% 
      distinct() %>% mutate(hvar = c(0), vvar = c(1)) 
    
    dist_ranks[[study_var]] <- actual_obs_markers$distance_rank_n[1]
    
    hist_plot <- hist_plot + 
      geom_histogram(data = temp_df, aes(x = std_co, fill = study), 
                     color = NA, 
                     position = "identity", 
                     alpha = 0.3,
                     breaks = bin_sequence)+
      geom_vline(
        data = actual_obs_markers,
        aes(xintercept = actual_std, color = study),
        size = 1.5#,
        # linetype = "longdash"
      )+
      geom_label(
        data = actual_obs_markers, 
        aes(y = Inf, x = -Inf,
            hjust = hvar, vjust = vvar,
            label = paste(c("SD: ", round(actual_std, 3), "\nObs. CO: ", actual), collapse = "")),
        fill = "white",
        color = "black",
        label.padding = unit(0.35, 'lines'),
        size = rel(6.5),
        hjust = "inward",
        show.legend = FALSE
      )
  }
  
  hist_plot <- hist_plot + 
    scale_x_continuous(breaks = seq(-4, 4, 1), limits = c(-4, 4))+
    scale_fill_manual(values = two_var_coloring, guide = "none")+
    scale_color_manual(values = two_var_coloring, guide = "none")+
    labs(x = "", y = "Count", title = paste(pathogens#, 
                                            # paste(c("(Mean Rank: ", round(mean(unlist(dist_ranks)), 3), ")"), collapse = "")
                                            ))+
    theme(
      panel.background = element_blank(), 
      strip.text = element_text(size = rel(1.2)),
      axis.text = element_text(size = rel(1.2)),
      strip.background = element_blank(),
      plot.title = element_markdown(size = rel(1.9)),
      # strip.text = element_blank(),
      panel.border = element_rect(fill = NA, color = "lightgray")
    )+ 
    facet_grid(study~.)
  return(hist_plot)
}

import_all_ensembles <- function(include_percentiles){
  simple_specs <- list()
  
  simple_specs[[1]] <- list(
    "filename" = "17d848d9-f7e0-4cd5-94b9-830b9b83f2b5", 
    "stool_type" = "Diarrhea",
    "data_type" = "complete_data", 
    "study" = "provide"
  )
  
  simple_specs[[2]] <- list(
    "filename" = "929e1537-00cb-4576-b2c8-579c8c561e65", 
    "stool_type" = "Asymptomatic",
    "data_type" = "complete_data", 
    "study" = "provide"
  )
  
  simple_specs[[3]] <- list(
    # "filename" = "baab7727-da3b-44f0-969b-a06d121c3b96",
    "filename" = "e1b4b5d7-1dd5-4c85-96e7-1d99dc1c6e54", # The Changed to invclue 3 additionl pathogens
    "stool_type" = "Diarrhea",
    "data_type" = "complete_data", 
    "study" = "maled"
  )
  
  simple_specs[[4]] <- list(
    "filename" = "5b9a8497-c577-4c21-aca1-1a58b55d7f01", 
    "stool_type" = "Asymptomatic",
    "data_type" = "complete_data", 
    "study" = "maled"
  )
  all_dfs <- list()
  for(l in simple_specs){
    # print(paste0("EXP_", l[["filename"]], '.csv'))
    if(include_percentiles){
      all_dfs[[l[['filename']]]] <- read_in_ensemble(
        paste0("EXP_", l[['filename']], '.csv'), top_ranked_pathogens, l[['study']], l[['stool_type']], include_percentiles)
    }else{
      all_dfs[[l[['filename']]]] <- read_in_ensemble(
        paste0("EXP_", l[['filename']], '.csv'), all_simple_results, l[['study']], l[['stool_type']], include_percentiles)
    }
  }
  
  return(do.call(rbind, all_dfs))
  
}

combine_like_pathogens <- function(d_f){
  all_etec <- d_f %>% select(one_of(c("st_etec", "etec", "lt_etec"))) %>% rowSums(.)
  
  new_etec <- (all_etec > 0) * 1
  
  final <- cbind(
    d_f %>% select(-one_of(c("st_etec", "lt_etec", "etec"))), 
    etec = new_etec
  ) %>% 
    rename(
      epec = `typical epec`
    ) %>% 
    select(
      - `atypical epec`
    )
  
  return(final)
  
}

filter_out_symmetric <- function(d_f){
  final <- d_f %>% 
    mutate(path1_switch = ifelse(path1 > path2, path1, path2),
           path2_switch = ifelse(path1 > path2, path2, path1)) %>% 
    select(-path1, -path2) %>% 
    rename(path1 = path1_switch, path2 = path2_switch) %>% 
    select(path1, path2, everything()) %>% 
    filter(path1 != path2) %>% 
    distinct()
  return(final)
}

#####

original_df <- import_complete_datasets(parent_dir = "data") %>% combine_like_pathogens()
all_simple_results <- get_all_simple_results(original_df, parent_dir = file.path("data", "null_ensembles", "datatables")) 

# Filtering out >10 is what removes all the pathogens. 
top_ranked_pathogens <- all_simple_results %>% 
  # filter_out_nonsymmetric() %>%
  filter_out_symmetric() %>%
  # filter_out_redundancies() %>%
  filter(actual > CO_MINIMUM) %>%
  group_by(study, stool_type) %>%
  mutate(percentile = as.numeric(percentile)) %>% 
  mutate(percentile_rank = rank(percentile, ties.method = "average"), 
         distance_rank = rank(-abs(0.5 - percentile), ties.method = "average"), 
         distance = abs(0.5 - percentile)) %>%
  mutate(percentile_rank_n = percentile_rank/max(percentile_rank), 
         distance_rank_n = distance_rank/max(distance_rank)) %>% 
  mutate(top10_distance = distance_rank < max(distance_rank) * 0.1) %>% 
  ungroup() %>% group_by(path1, path2, stool_type) %>% 
  mutate(top10_both = sum(top10_distance) > 1)

all_ensembles <- import_all_ensembles(include_percentiles = TRUE)  %>% 
  mutate(study = case_when(study == "maled" ~ "MAL-ED", 
                           study == "provide" ~ "PROVIDE"))

plot_pathogen_pair_distribution(all_ensembles, 'pdf')


# all_ensembles

